version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-container
    command: redis-server --appendonly yes --save 60 1 --dir /data
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped

  theatre-db:
    image: postgres:16
    container_name: postgres-container
    env_file:
      - ./etl/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
     - 5432:5432
    restart: unless-stopped
    depends_on:
      - redis

  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: elasticsearch-container
    restart: always
    ports:
      - 9200:9200
    volumes:
      - es:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  celery-worker:
    environment:
      DB_HOST: theatre-db
      ELASTIC_HOST: elasticsearch
      REDIS_HOST: redis
    build: ./etl/
    container_name: celery-worker-container
    command: celery -A celery worker -l INFO -E -P gevent
    env_file: ./etl/.env
    restart: unless-stopped
    depends_on:
      - redis
      - theatre-db

  celery-beat:
    environment:
      DB_HOST: theatre-db
      ELASTIC_HOST: elasticsearch
      REDIS_HOST: redis
    build: ./etl/
    container_name: celery-beat-container
    command: celery -A celery beat -l INFO
    env_file: ./etl/.env
    restart: unless-stopped
    depends_on:
      - redis
      - theatre-db

volumes:
  redis_data:
  pg_data:
  es:

